/** Action UUIDs; must match manifest.json */
export const UUID = {
	PLAYBACK: "sh.cider.streamdeck.playback",
	SONGNAME: "sh.cider.streamdeck.songname",
	ALBUMART: "sh.cider.streamdeck.albumart",
	TOGGLE: "sh.cider.streamdeck.toggle",
	REPEAT: "sh.cider.streamdeck.repeat",
	SHUFFLE: "sh.cider.streamdeck.shuffle",
	VOLUME_UP: "sh.cider.streamdeck.volumeup",
	VOLUME_DOWN: "sh.cider.streamdeck.volumedown",
	ADD_TO_LIBRARY: "sh.cider.streamdeck.addtolibrary",
	DISLIKE: "sh.cider.streamdeck.dislike",
	LIKE: "sh.cider.streamdeck.like",
	SKIP: "sh.cider.streamdeck.skip",
	PREVIOUS: "sh.cider.streamdeck.previous",
	CIDER_LOGO: "sh.cider.streamdeck.ciderlogo",
	ATMOS: "sh.cider.streamdeck.atmos",
	CROSSFADE: "sh.cider.streamdeck.crossfade",
	AUTOMIX: "sh.cider.streamdeck.automix",
	LISTENING_MODE: "sh.cider.streamdeck.listeningmode",
	QUEUE_CLEAR: "sh.cider.streamdeck.queueclear",
	SMART_QUEUE: "sh.cider.streamdeck.smartqueue",
	QUEUE_DIAL: "sh.cider.streamdeck.queuedial",
	PINNED_ITEM: "sh.cider.streamdeck.pinneditem",
	ALBUM_ART_GRID: "sh.cider.streamdeck.albumartgrid",
} as const;
